#!/bin/bash

echo "🔍 Tafsir 详细诊断脚本"
echo "================================"
echo ""
echo "步骤 1: 编译应用"
echo "./gradlew :app:assembleDebug"
echo ""
echo "步骤 2: 卸载并安装"
echo "adb uninstall com.quran.quranaudio.online"
echo "adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo "步骤 3: 清空并监控日志（在另一个终端窗口运行）"
echo "adb logcat -c"
echo "adb logcat | grep -E 'TafsirManager|MainActivity.*Tafsir|ActivityTafsir'"
echo ""
echo "步骤 4: 在手机上打开应用"
echo "1. 打开应用"
echo "2. 打开古兰经任意经文"
echo "3. 点击 Tafsir（注释）按钮"
echo ""
echo "📊 观察日志，应该看到："
echo "   TafsirManager: 🔧 prepare called"
echo "   TafsirManager: 📥 loadTafsirs called"
echo "   TafsirManager: 📂 Tafsir manifest file: ..."
echo "   TafsirManager: 📄 Loading from local file... 或 🌐 Force loading from network..."
echo "   TafsirManager: ✅ Parsed X language groups"
echo "   MainActivity: ✅ Auto-selected and saved Tafsir: xxx"
echo ""
echo "如果看到 ❌ 或 ⚠️ 日志，请复制完整日志给我！"
