#!/bin/bash

echo "📋 Tafsir 印尼语问题诊断脚本"
echo "================================"
echo ""
echo "🔍 请按照以下步骤操作，并观察日志输出："
echo ""
echo "步骤 1: 启动日志监控（在新终端窗口运行）"
echo "--------------------------------"
echo "adb logcat | grep -E 'MainActivity.*Tafsir|TafsirManager|TafsirLanguageMapper|SPReader.*Tafsir'"
echo ""
echo ""
echo "步骤 2: 清除应用数据并重新安装"
echo "--------------------------------"
echo "adb uninstall com.quran.quranaudio.online"
echo "adb install app/build/outputs/apk/debug/app-debug.apk"
echo ""
echo ""
echo "步骤 3: 在手机上操作"
echo "--------------------------------"
echo "1. 打开应用"
echo "2. 在引导页选择 '印尼语（Bahasa Indonesia）'"
echo "3. 完成引导流程"
echo "4. 打开古兰经任意经文"
echo "5. 点击 Tafsir（注释）按钮"
echo ""
echo ""
echo "📊 观察日志中的关键信息："
echo "--------------------------------"
echo "✅ 期望看到："
echo "   MainActivity: 🔧 No Tafsir selected, initializing default Tafsir..."
echo "   MainActivity: 🌍 Target language for Tafsir: id"
echo "   MainActivity: ✅ Auto-selected and saved Tafsir: id-tafsir-xxx"
echo ""
echo "❌ 如果看到："
echo "   MainActivity: ⚠️ No Tafsir models available"
echo "   MainActivity: ⚠️ No suitable Tafsir found for language: id"
echo ""
echo "   说明 Tafsir 数据加载有问题"
echo ""
