#!/bin/bash

echo "═══════════════════════════════════════════════"
echo "🎯 完整原生广告测试脚本"
echo "═══════════════════════════════════════════════"
echo ""

LOG_FILE="all_native_ads_test.txt"

echo "1️⃣ 清空日志..."
adb logcat -c
echo "✅ 日志已清空"
echo ""

echo "📝 开始记录日志..."
echo "日志将保存到: $LOG_FILE"
echo ""

echo "═══════════════════════════════════════════════"
echo "📋 测试步骤："
echo "═══════════════════════════════════════════════"
echo ""
echo "【步骤1】启动应用并检查主页"
echo "  1. 在Android Studio重新编译运行"
echo "  2. 跳过onboarding，进入主页"
echo "  3. 确认你在主页Tab（底部第一个）"
echo "  4. 向下滚动到 Verse of the Day 卡片"
echo "  5. 查看卡片底部是否有原生广告"
echo ""
echo "【步骤2】测试Quiz答题结果页"
echo "  1. 点击 Quiz 或 Review & Learn"
echo "  2. 开始答题（随便答）"
echo "  3. 完成答题，查看结果页"
echo "  4. 向下滚动到页面底部"
echo "  5. 查看是否有原生广告"
echo ""
echo "═══════════════════════════════════════════════"
echo "🔍 关键日志检查点："
echo "═══════════════════════════════════════════════"
echo ""
echo "【主页】应该看到："
echo "  ✓ MainActivity.onCreate() START"
echo "  ✓ Setting start destination: HOME"
echo "  ✓ HomeFragment.onAttach() CALLED"
echo "  ✓ HomeFragment.onCreateView() START"
echo "  ✓ HomeFragment.initializeVerseOfDayCard() CALLED"
echo "  ✓ HomeFragment.loadVOTDNativeAd() CALLED"
echo ""
echo "【Quiz】应该看到："
echo "  ✓ Quiz Result Page - preloadNativeAd() CALLED"
echo "  ✓ AdNativeSmallWrapperView.loadNativeAd() CALLED"
echo "  ✓ Native ad displayed successfully"
echo "  ✓ Ad Visibility Check (after 2s)"
echo "  ✓ Ad has X child views"
echo ""
echo "═══════════════════════════════════════════════"
echo "📊 开始记录日志..."
echo "按 Ctrl+C 停止监控"
echo "═══════════════════════════════════════════════"
echo ""

adb logcat | grep -E "NATIVE_AD_TRACK|MainActivity.*onCreate|HomeFragment|QuizReviewLearnActivity" | tee "$LOG_FILE"

