plugins {
    id 'com.android.library'
}

android {
    compileSdk 35
    defaultConfig {
        minSdkVersion 26
        targetSdkVersion 35
        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    namespace 'com.raiadnan.ads.sdk'
    lint {
        disable 'GradleDependency', 'ExpiringTargetSdkVersion'
    }
    
    // ===== 16 KB Page Size Support =====
    packagingOptions {
        jniLibs {
            useLegacyPackaging = true
        }
    }
}

dependencies {

    implementation fileTree(dir: 'libs', include: ['*.aar', '*.jar'], exclude: [])
    implementation 'androidx.appcompat:appcompat:1.2.0'
    implementation 'com.google.android.material:material:1.9.0'
    implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'
    implementation 'com.google.android.gms:play-services-appset:16.0.2'
    implementation 'com.google.android.gms:play-services-basement:18.2.0'

    //Primary Ad Networks
    implementation 'com.google.android.gms:play-services-ads:22.1.0'
    
    // Unity Ads - Bidding (统一版本)
    implementation 'com.unity3d.ads:unity-ads:4.8.0'
    
    // Meta Audience Network (Facebook) - Bidding (统一版本)
    implementation 'com.facebook.android:audience-network-sdk:6.14.0'

    //AdMob mediation - Bidding
    implementation 'com.google.ads.mediation:unity:4.16.0.1'
    implementation 'com.google.ads.mediation:facebook:6.14.0.0'

    //Unity ads mediation
    implementation 'com.unity3d.mediation:mediation-sdk:1.1.0'
    implementation 'com.unity3d.mediation:unityads-adapter:1.1.0'
    implementation 'com.unity3d.mediation:admob-adapter:1.1.0'
    implementation 'com.unity3d.mediation:facebook-adapter:1.1.1'

    //GDPR
    implementation 'com.google.android.ump:user-messaging-platform:2.0.0'
    implementation 'com.google.android.ads.consent:consent-library:1.0.8'
}
