[versions]
coreKtx = "1.9.0"
lifecycle = "2.5.1"
desugaring = "1.1.5"
annotation = "1.5.0"
legacySupport = "1.0.0"
appcompat = "1.6.0"
material = "1.8.0"
constraintlayout = "2.1.4"
apacheCommons = "3.12.0"
guava = "31.0.1-jre"
webkit = "1.6.0"
media = "1.6.0"
viewbinding = "7.4.1"
browser = "1.4.0"
exoplayer = "2.18.5"
swipeRefreshLayout = "1.7.2.4"
retrofit = "2.9.0"
kotlinxSerialization = "1.4.1"
kotlinxRetrofit = "0.8.0"
kotlinBom = "1.8.0"
junit = "4.13.2"
junitVersion = "1.1.5"
espressoCore = "3.5.1"

[libraries]
androidx-coreKtx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
lifecycle-service = { group = "androidx.lifecycle", name = "lifecycle-service", version.ref = "lifecycle" }
lifecycle-runtime = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-legacySupport = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupport" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-media = { group = "androidx.media", name = "media", version.ref = "media" }
desugaring = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugaring" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
apache-commons = { group = "org.apache.commons", name = "commons-lang3", version.ref = "apacheCommons" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
viewbinding = { group = "com.android.databinding", name = "viewbinding", version.ref = "viewbinding" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "browser" }

# ExoPlayer
exoplayerCore = { group = "com.google.android.exoplayer", name = "exoplayer-core", version.ref = "exoplayer" }
exoplayerUI = { group = "com.google.android.exoplayer", name = "exoplayer-ui", version.ref = "exoplayer" }
extensionMediasession = { group = "com.google.android.exoplayer", name = "extension-mediasession", version.ref = "exoplayer" }

# SmoothRefreshLayout
srlCore = { group = "com.github.dkzwm", name = 'srl-core', version.ref = "swipeRefreshLayout" }
srlExtClassics = { group = "com.github.dkzwm", name = 'srl-ext-classics', version.ref = "swipeRefreshLayout" }
srlExtMaterial = { group = "com.github.dkzwm", name = 'srl-ext-material', version.ref = "swipeRefreshLayout" }
srlExtDynamicRebound = { group = "com.github.dkzwm", name = 'srl-ext-dynamic-rebound', version.ref = "swipeRefreshLayout" }
srlExtHorizontal = { group = "com.github.dkzwm", name = 'srl-ext-horizontal', version.ref = "swipeRefreshLayout" }
srlExtTwoLevel = { group = "com.github.dkzwm", name = 'srl-ext-two-level', version.ref = "swipeRefreshLayout" }
srlExtUtil = { group = "com.github.dkzwm", name = 'srl-ext-util', version.ref = "swipeRefreshLayout" }

retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
kotlinxSerialization = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerialization" }
kotlinxRetrofit = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinxRetrofit" }
kotlin-bom = { group = "org.jetbrains.kotlin", name = "kotlin-bom", version.ref = "kotlinBom" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }