package com.bible.tools.ad

object FunctionTag {
    const val MARK = "mark"
    const val AMEN = "amen"
    const val VERSE_MOOD_JOURNAL = "verse_mood_journal"
    const val VERSE_MOOD_CHOICE = "verse_mood_choice"
    const val VERSE_MOOD_NOTE = "verse_mood_note"
    const val VERSE_MOOD_CHOICE_EXIT = "verse_mood_choice_exit"
    const val VERSE_MOOD_NOTE_EXIT = "verse_mood_note_exit"
    const val VERSE_MOOD_RECORD_EXIT = "verse_mood_record_exit"
    const val VERSE_MOOD_RESULT_EXIT = "verse_mood_result_exit"
    const val QUESTION_TIPS = "question_tips"
    const val QUESTION_FAIL_SKIP = "question_fail_skip"
    const val QUESTION_FAIL_TRY_AGAIN = "question_fail_try_again"
    const val QUESTION_FAIL_RELIVE_REWARD = "question_fail_relive_reward"
    const val QUESTION_FAIL_RELIVE_INTER = "question_fail_relive_inter"
    const val PRAYER_VERSE = "prayer_verse"
    const val PRAYER_ANIMATOR = "prayer_animator"
    const val PLAN_MARK = "plan_mark"
    const val PRAYER_RESULT = "prayer_result"
    const val MOOD_CALENDAR = "mood_calendar"
    const val QUESTION_NEXT_LEVEL = "question_next_level"
    const val QUESTION_NEXT_REWARD = "question_next_reward"
    const val QUESTION_NEXT_INTERS = "question_next_inters"
    const val QUESTION_FREE_REWARD = "question_free_reward"
    const val QUESTION_FREE_INTERS = "question_free_inters"
    const val QUESTION_DAILY_REWARD = "question_daily_reward"
    const val QUESTION_DAILY_INTERS = "question_daily_inters"
    const val QUESTION_MORE_REWARD = "question_more_reward"
    const val QUESTION_MORE_INTERS = "question_more_inters"
    const val ACTIVITY_FLOAT_WINDOW_OPEN = "activityFloatWindow_open"
    const val SPLASH_OPEN = "splash_open"


    const val NATIVE_AMEN_RESULT = "native_amen_result"
    const val NATIVE_BIBLE_RESULT = "native_bible_result"
    const val NATIVE_QUIZ = "native_quiz"
    const val NATIVE_ME = "native_me"
    const val NATIVE_PRAYER_VERSE = "native_prayer_verse"
    const val NATIVE_HOME = "native_home"
    const val NATIVE_PLAN_DETAIL = "native_plan_detail"
    const val NATIVE_PLAN_STUDY_DETAIL = "native_plan_study_detail"
    const val NATIVE_QUIZ_FAIL = "native_quiz_fail"
    const val VERSE_HOME = "verse_home"
    const val NATIVE_PLAN_LIST = "native_plan_list"
    const val NATIVE_PLAN_LIST_2 = "native_plan_list_2"
    const val NATIVE_HOME_BACK_AD = "home_back_ad"
    const val NATIVE_QUIZ_RELIVE = "native_quiz_relive"


}